spring:
  datasource:
    url: jdbc:mysql://rm-2ze34z31901fe8lrnbo.mysql.rds.aliyuncs.com/ai_smartdevice?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: zhangbo123
    password:
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
