server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://rm-2ze34z31901fe8lrnbo.mysql.rds.aliyuncs.com/ai_smartdevice?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: zhangbo123
    password:
    type: com.alibaba.druid.pool.DruidDataSource

picture:
  url: https://hlbr.smartdeviceclub.com

http:
  server:
    port: 8088

device:
  img: https://hlbr.smartdeviceclub.com/home/img/d7dcd2deb11840af8b40cd93f800b116.png
  collectspace: 30