server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://:3306/ai_smartdevice?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource

picture:
  url: http://localhost:8080

http:
  server:
    port: 8088