server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///ai_smartdevice?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: dev_ai
    password:
    type: com.alibaba.druid.pool.DruidDataSource

picture:
  url: http://localhost:8080