server:
  ssl:
    key-store: classpath:hlbr.smartdeviceclub.com.jks
    key-store-password: hlbr.smartdeviceclub.com
spring:
  profiles:
    active: prod
  servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB