server:
  port: 443
spring:
  datasource:
    url: jdbc:mysql://rm-2ze34z31901fe8lrnbo.mysql.rds.aliyuncs.com/ai_smartdevice?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: zhangbo123
    password:
    type: com.alibaba.druid.pool.DruidDataSource

picture:
  url: http://114.55.171.27

http:
  server:
    port: 80