server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.16.16.106:3306/ai_smartdevice?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false
    username: dev_ai
    password: ziroomdb
    type: com.alibaba.druid.pool.DruidDataSource

picture:
  url: http://localhost:8080